routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// *** v1 ***
Route::group(['namespace' => 'View\v1'], function () { 
	Route::group(['middleware' => 'language'], function () { // 語系

		Route::get('/', 'ViewController@home')->name('home');
		Route::get('/admin', 'ViewController@admin_home')->name('admin_home');								
		Route::get('/register/{recommender_account}', 'ViewController@register')->middleware('register')->name('register');
        Route::get('/intro', 'ViewController@intro')->name('front.intro');
        Route::get('/report', 'ViewController@bet_report')->name('bet_report');

        //Route::get('/test', 'ViewController@test')->name('test');

		// User
		Route::group(['middleware' => 'viewUser'], function () {
		    Route::get('/user/news', 'ViewController@user_news')->name('user_news'); 
		    //Route::get('/user/org/branch/{account}', 'ViewController@user_org_branch_specific')->name('user_org_branch_specific'); 
		    Route::get('/user/org/recommend/{account}', 'ViewController@user_org_recommend_specific')->name('user_org_recommend_specific');
		    Route::get('/user/account', 'ViewController@user_account')->name('user_account');
		    Route::get('/user/active', 'ViewController@user_active')->name('user_active');
		    Route::get('/user/transform', 'ViewController@user_transform')->name('user_transform');
		    Route::get('/user/trade', 'ViewController@user_trade')->name('user_trade');
		    Route::get('/user/wallet', 'ViewController@user_wallet')->name('user_wallet');		  
		    Route::get('/user/game', 'ViewController@user_game')->name('user_game');
		    Route::get('/user/withdraw', 'ViewController@user_withdraw')->name('user_withdraw');		    
		    Route::get('/user/ask', 'ViewController@user_ask')->name('user_ask');		  
		    Route::get('/user/pay', 'ViewController@user_pay')->name('user_pay');
		    Route::get('/user/pay/vbank/{pay_id}', 'ViewController@user_pay_vbank')->name('api.pay.tc.vbank.id');		      

		});
		// Admin
		Route::group(['middleware' => 'viewAdmin'], function () {
			Route::get('/admin/control', 'ViewController@admin_control')->name('admin_control');
			Route::get('/admin/manage/account', 'ViewController@admin_manage_account')->name('admin_manage_account');
			Route::get('/admin/manage/account/{user_id}', 'ViewController@admin_manage_account_specific')->name('admin_manage_account_specific');
			Route::get('/admin/manage/branch/{user_id}', 'ViewController@admin_manage_branch')->name('admin_manage_branch');
			Route::get('/admin/manage/recommend/{user_id}', 'ViewController@admin_manage_recommend')->name('admin_manage_recommend');			
			Route::get('/admin/trade', 'ViewController@admin_trade')->name('admin_trade');
			Route::get('/admin/info', 'ViewController@admin_info')->name('admin_info');
			Route::get('/admin/withdraw', 'ViewController@admin_withdraw')->name('admin_withdraw');
			//Route::get('/admin/calender', 'ViewController@admin_calender')->name('admin_calender'); // admin 倍率日曆
			Route::get('/admin/ask', 'ViewController@admin_ask')->name('admin.ask');
		});



	}); // end middleware language
}); // end v1

app/Models/ActiveRecord.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ActiveRecord extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'active_record';
}

app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;




class Admin extends Model
{
   // use SoftDeletes;
   protected $table = 'admin';
}

app/Models/Ask.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ask extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'ask';
}

app/Models/Ball.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ball extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'ball';
}

app/Models/BetReport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BetReport extends Model
{
    //
}

app/Models/Frozen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Frozen extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'frozen';
}

app/Models/Log.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Log extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'log';
}

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'order';
}

app/Models/OrderWithdraw.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class OrderWithdraw extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'order_withdraw';
}

app/Models/Pay.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Pay extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'pay';
}

app/Models/PhoneVerify.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PhoneVerify extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'phone_verify';
}

app/Models/Rate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Rate extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'rate';
}

app/Models/System.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class System extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'system';
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'tag';
}

app/Models/Trading.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Trading extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'trading';
}

app/Models/Transaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Transaction extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'transaction';
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'user';
}

app/Models/Wallet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Wallet extends Model
{
   use SoftDeletes;
   protected $dates = ['deleted_at'];
   
   protected $table = 'wallet';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/_admin/calender.blade.php
@extends('layouts.admin_app') 


@push('head')
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/u_calender.css') }}">	
    <style type="text/css">
		
		.nori_title{
			font-size: 20px;
		}

		#wrap {
			width: 1100px;
			margin: 0 auto;
			}
			
		#external-events {
			float: left;
			width: 150px;
			padding: 0 10px;
			text-align: left;
			}
			
		#external-events h4 {
			font-size: 16px;
			margin-top: 0;
			padding-top: 1em;
			}
			
		.external-event { /* try to mimick the look of a real event */
			margin: 10px 0;
			padding: 2px 4px;
			background: #3366CC;
			color: #fff;
			font-size: .85em;
			cursor: pointer;
			}
			
		#external-events p {
			margin: 1.5em 0;
			font-size: 11px;
			color: #666;
			}
			
		#external-events p input {
			margin: 0;
			vertical-align: middle;
			}

		#calendar {
	/* 		float: right; */
	        margin: 0 auto;
			width: 900px;
			background-color: #FFFFFF;
			  border-radius: 6px;
	        box-shadow: 0 1px 2px #C3C3C3;
			-webkit-box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
	-moz-box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
	box-shadow: 0px 0px 21px 2px rgba(0,0,0,0.18);
			}


    </style>

@endpush


@push('script')
	<script src="{{ asset('js/u_jquery.dataTables.min.js') }}"></script>
	<script src="{{ asset('js/admin/u_api_mgr_admin.js') }}"></script>
	<script src="{{ asset('js/admin/u_common.js') }}"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" ></script>	
  	<script src="{{ asset('js/u_calender.js') }}"></script>	
	<script type="text/javascript">

			
		$(document).ready(function() {
		　		
		  setTimeout(function(){
		      //nori_show_calender();
		      getDividendRates();
		  },500);
			
		});


		// ＊＊ 取得目前已存倍率 ＊＊
		var m_calender_title_array = [];
		function getDividendRates(){

		  m_calender_title_array = [];
		  p_ApiMgr_admin.getDividendRates(

		        function (result) {
		        	//console.log('aaaa = '+ result['aaaa']);
		        	for (var i = result.length - 1; i >= 0; i--) {
		        		
		        		push_title(
		        			      result[i].year
		        				  , result[i].month
		        				  , result[i].day
		        				  , result[i].rate
		        				  );
		        	}
		            nori_show_calender();

		                        
		        },this,
		        function (error) {},this
		  );

		  return false;
		}




		function addDividendRates(input_year, input_month, input_day, input_content){

			  p_ApiMgr_admin.addDividendRates(
			        	input_year,
			        	input_month,
			        	input_day,
			        	input_content,
			        function (result) {
			        	// 後端會加入一筆資料, 然後重吐全部回來
			        	//console.log(result);
			        	m_calender_title_array = [];
			        	for (var i = result.length - 1; i >= 0; i--) {
			        		
			        		push_title(
			        			      result[i].year
			        				  , result[i].month
			        				  , result[i].day
			        				  , result[i].rate
			        				  );
			        	}
			            nori_show_calender();

			                        
			        },this,
			        function (error) {},this
			  );

			
		//console.log(m_calender_title_array);
		}



		// ＊＊＊　把收到的倍率資訊　丟到陣列　秀出來　＊＊＊
		
		function push_title(input_year, input_month, input_day, input_content){

			var title_obj = {};
			title_obj.title = '<span class="nori_title">'+input_content+'%</span>';
			title_obj.start = new Date(input_year, input_month, input_day);


			m_calender_title_array.push(title_obj);

			// 先檢查有沒有重複的那天, 有的畫覆蓋過去
			// var is_titled = false;
			// for (var i = m_calender_title_array.length - 1; i >= 0; i--) {
			// 	var _day   = m_calender_title_array[i].start.getDate();
			// 	var _month = m_calender_title_array[i].start.getMonth();
			// 	var _year  = m_calender_title_array[i].start.getFullYear();

			// 	if(_day == input_day && _month == input_month && _year == input_year){
			// 		m_calender_title_array[i] = title_obj;
			// 		is_titled = true;
			// 		break;
			// 	}
			// }

			// // 沒有重複的日期, 才新寫入
			// if(!is_titled){
			// 	m_calender_title_array.push(title_obj);
			// }
			
			//console.log(m_calender_title_array);
		}


		// ＊＊＊　日曆顯示　＊＊＊
		function nori_show_calender(){

				$('#calendar').html('');
			    var date = new Date();
				var d = date.getDate();
				var m = date.getMonth();
				var y = date.getFullYear();
				
				/*  className colors
				
				className: default(transparent), important(red), chill(pink), success(green), info(blue)
				
				*/		
				
				  
				/* initialize the external events
				-----------------------------------------------------------------*/
			
				$('#external-events div.external-event').each(function() {
					
					// create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
					// it doesn't need to have a start or end
					var eventObject = {
						title: $.trim($(this).text()) // use the element's text as the event title
					};
		
					// store the Event Object in the DOM element so we can get to it later
					$(this).data('eventObject', eventObject);
					
					// make the event draggable using jQuery UI
					$(this).draggable({
						zIndex: 999,
						revert: true,      // will cause the event to go back to its
						revertDuration: 0  //  original position after the drag
					});
					
				});
			
			
				/* initialize the calendar
				-----------------------------------------------------------------*/
				
				var calendar =  $('#calendar').fullCalendar({
					header: {
						left: 'title',
						center: 'month',
						right: 'prev,next today'
					},
					editable: true,
					firstDay: 1, //  1(Monday) this can be changed to 0(Sunday) for the USA system
					selectable: true,
					defaultView: 'month',
					
					axisFormat: 'h:mm',
					columnFormat: {
		                month: 'ddd',    // Mon
		                week: 'ddd d', // Mon 7
		                day: 'dddd M/d',  // Monday 9/7
		                agendaDay: 'dddd d'
		            },
		            titleFormat: {
		                month: 'MMMM yyyy', // September 2009
		                week: "MMMM yyyy", // September 2009
		                day: 'MMMM yyyy'                  // Tuesday, Sep 8, 2009
		            },
					allDaySlot: false,
					selectHelper: true,
					select: function(start, end, allDay) {
						
						// 如果日期比明天小 return  date start
						if(Date.parse(date+1).valueOf() > Date.parse(start).valueOf()){
							console.log('日期小於今日');
							return;
						}

						var title = prompt(start.toLocaleDateString()+' 請輸入倍率數字');
						if (title) {
							//console.log('留言: 開始時間 start = '+start.toLocaleDateString()+' , 留言內容 = '+title);
							var _local_day = start.getDate();
							var _local_month = start.getMonth();
							var _local_year = start.getFullYear();
							addDividendRates(_local_year,_local_month,_local_day,title);
							//nori_show_calender();
							// calendar.fullCalendar('renderEvent',
							// 	{
							// 		title: title,
							// 		start: start,
							// 		end: end,
							// 		allDay: allDay
							// 	},
							// 	true // make the event "stick"
							// );
							
						}
						//calendar.fullCalendar('unselect');
					},
					droppable: true, // this allows things to be dropped onto the calendar !!!
					drop: function(date, allDay) { // this function is called when something is dropped
						
						// retrieve the dropped element's stored Event Object
						var originalEventObject = $(this).data('eventObject');

						// we need to copy it, so that multiple events don't have a reference to the same object
						var copiedEventObject = $.extend({}, originalEventObject);
						
						// assign it the date that was reported
						copiedEventObject.start = date;
						copiedEventObject.allDay = allDay;
						
						// render the event on the calendar
						// the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
						$('#calendar').fullCalendar('renderEvent', copiedEventObject, true);
						
						// is the "remove after drop" checkbox checked?
						if ($('#drop-remove').is(':checked')) {
							// if so, remove the element from the "Draggable Events" list
							$(this).remove();
						}
						
					},
					
					events: 
						m_calender_title_array
						// {
						// 	title: '<span class="nori_title">1.2</span>',
						// 	start: new Date(y, m, 1)
						// },
						// {
						// 	title: '<span class="nori_title">1.8</span>',
						// 	start: new Date(y, m, 15)
						// },					

					,			
				});

		}



	</script>

@endpush


@section('content')

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">      		
		<div style="display:inline-block">
			<h2>{{ Lang::get('admin.dividend_setting')}}</h2>
		</div>
		<div class="web_map">	
			&nbsp;&nbsp;&nbsp;{{ Lang::get('user.main_page')}}
			&nbsp;>&nbsp;{{ Lang::get('admin.dividend_setting')}}
		</div>
	</div>
</div>

<hr align="left" width="20%" class="site_map_hr">

<!-- 日曆 -->
<div id='wrap' style="position: relative;left: -80px;">
	<div id='calendar'></div>

	<div style='clear:both'></div>
</div>


@endsection

resources/views/_transform/user_transform.blade.php
@extends('layouts.user') 

@push('head')
	    
@endpush

@push('script')
	<script src="{{ asset('js/u_my_utility.js') }}"></script>
	<script type="text/javascript">
		
		
		// ＊＊ ready-jobs ＊＊
		$(function(){
			
        	$("#div_colorpoint").hide();
		   	getPoint();

   	        setTimeout(function(){
				if(p_is_colorpoint == 1){	
				$("#div_colorpoint").show();			
					getColorPoint();
				}	
        	},500);
	  		//checkIsColorpoint();

		})


		// ＊＊ 取得配套和點數 ＊＊
		function getPoint(){

		  p_ApiMgr.getPoint(

		        function (result) {

		            $("#show_point").val(toDecimal2(result));

		        },this,
		        function (error) {},this
		  );


		  return false;
		}


	    // ＊＊ 檢查用點數還是彩點 ＊＊
	    // var m_is_colorpoint = false;
	    // function checkIsColorpoint(){

	    //   p_ApiMgr.checkIsColorpoint(

	    //         function (result) {
	    //             console.log(result['is_colorpoint']);
	    //             m_is_colorpoint = result['is_colorpoint'];
					// if(m_is_colorpoint == 1){	
					// $("#div_colorpoint").show();			
					// 	getColorPoint();
					// }	                

	    //         },this,
	    //         function (error) {},this
	    //   );


	    //   return false;
	    // }


		// ＊＊ 取得彩點 ＊＊
		function getColorPoint(){

		  p_ApiMgr.getColorPoint(

		        function (result) {

		            $("#show_colorpoint").val(toDecimal2(result));

		        },this,
		        function (error) {},this
		  );


		  return false;
		}

		function openModal(){


		  if($("#deposit_pt_acc").val() == '' || $("#outward_pt_amount").val() == ''){
		    return false;
		  }

		  $("#span_tf_account").text( $("#deposit_pt_acc").val() );
		  $("#span_points").text( $("#outward_pt_amount").val() );  
		        //   <p>{{ Lang::get('user.account')}}&nbsp;<span id="span_tf_account"></span></p>
		        // <p>{{ Lang::get('user.point')}}&nbsp;<span id="span_points"></span></p>

		  $('#myModal').modal('toggle');

		}


		function openColorModal(){

		  if($("#deposit_cpt_acc").val() == '' || $("#outward_cpt_amount").val() == ''){
		    return false;
		  }

		  $("#span_color_tf_account").text( $("#deposit_cpt_acc").val() );
		  $("#span_color_points").text( $("#outward_cpt_amount").val() );  
		        //   <p>{{ Lang::get('user.account')}}&nbsp;<span id="span_tf_account"></span></p>
		        // <p>{{ Lang::get('user.point')}}&nbsp;<span id="span_points"></span></p>

		  $('#colorModal').modal('toggle');

		}


		// ＊＊ 轉出點數 ＊＊
		function depositPoints(){


		$('#myModal').modal('hide');
		  p_ApiMgr.depositPoints(
		          $("#deposit_pt_acc").val(),
		          $("#outward_pt_amount").val(),             
		        function (result) {
		            //console.log(result);
		            alert('贈與點數成功');
		            
		            location.reload();
		            //alert(result);
		        },this,
		        function (error) {
		          $('#myModal').modal('hide');
		        },this
		  );

		  return false;
		}


		// ＊＊ 轉出彩點 ＊＊
		function depositColorPoints(){

		  $('#colorModal').modal('hide');

		  p_ApiMgr.depositColorPoints(
		          $("#deposit_cpt_acc").val(),
		          $("#outward_cpt_amount").val(),             
		        function (result) {
		            //console.log(result);
		            alert('贈與彩點成功');
		            
		            location.reload();
		            //alert(result);
		        },this,
		        function (error) {
		          $('#myModal').modal('hide');
		        },this
		  );

		  return false;
		}



		

	</script>
@endpush

@section('content')
	
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">      		
		<div style="display:inline-block">
			<h2>{{ Lang::get('user.tranform_system')}}</h2>
		</div>
		<div class="web_map">		
			&nbsp;&nbsp;&nbsp;{{ Lang::get('user.main_page')}}
			&nbsp;>&nbsp;{{ Lang::get('user.tranform_system')}}
		</div>
	</div>
</div>

<hr align="left" width="20%" class="site_map_hr">

<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">      			
		
	   		<h2>{{ Lang::get('user.point')}}</h2>
	   	
		  	{{ Lang::get('user.cur_point')}}		  	
		  	<input type="text" class="form-control" id="show_point"  disabled>
		  	<br />	  

			<div class="form-group">
			  <label for="deposit_pt_acc">{{ Lang::get('user.tf_in_acc')}}</label>
			  <input type="text" class="form-control" id="deposit_pt_acc" maxlength="16">
			</div>
			<div class="form-group">
			  <label for="outward_pt_amount">{{ Lang::get('user.tf_out_pt_amount')}}</label>
			  <input type="text" class="form-control" id="outward_pt_amount" maxlength="10">
			</div>

			<button type="button" class="btn btn-success" onclick="openModal()">{{ Lang::get('user.tf_out')}}</button>	
			<br />		

		</div>



		<div id="div_colorpoint" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">      			
			<br /><br />
	   		<h2>{{ Lang::get('user.color_point')}}</h2>
	
		  	{{ Lang::get('user.cur_color_point')}}		  	
		  	<input type="text" class="form-control" id="show_colorpoint"  disabled>
		  	<br />	  

			<div class="form-group">
			  <label for="deposit_pt_acc">{{ Lang::get('user.tf_in_acc')}}</label>
			  <input type="text" class="form-control" id="deposit_cpt_acc" maxlength="16">
			</div>
			<div class="form-group">
			  <label for="outward_pt_amount">{{ Lang::get('user.tf_out_pt_amount')}}</label>
			  <input type="text" class="form-control" id="outward_cpt_amount" maxlength="10">
			</div>

			<button type="button" class="btn btn-success" onclick="openColorModal()">{{ Lang::get('user.tf_out')}}</button>	
			<br />		

		</div>

	</div>
</div>



<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">      		
		<br /><br /><br /><br /><br />
	</div>
</div>




<!-- point Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog" style="max-width: 98vw;">

    <!-- Modal content-->
    <div class="modal-content">
	
      <div class="modal-body">
        <p>{{ Lang::get('user.confirm_txn_out')}}</p>
        <p>{{ Lang::get('user.account')}}&nbsp;<span id="span_tf_account" style="color: blue;"></span></p>
        <p>{{ Lang::get('user.point')}}&nbsp;<span id="span_points" style="color: blue;"></span></p>
      </div>

      <div class="modal-footer">

      	<button type="button" class="btn btn-success" onclick="depositPoints()">{{ Lang::get('user.confirm')}}</button>	
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>


<!-- colorpoint Modal -->
<div id="colorModal" class="modal fade" role="dialog">
  <div class="modal-dialog" style="max-width: 98vw;">

    <!-- Modal content-->
    <div class="modal-content">
	
      <div class="modal-body">
        <p>{{ Lang::get('user.confirm_txn_out')}}</p>
        <p>{{ Lang::get('user.account')}}&nbsp;<span id="span_color_tf_account" style="color: blue;"></span></p>
        <p><span style="color: red;">{{ Lang::get('user.color_point')}}</span>&nbsp;<span id="span_color_points" style="color: blue;"></span></p>
      </div>

      <div class="modal-footer">

      	<button type="button" class="btn btn-success" onclick="depositColorPoints()">{{ Lang::get('user.confirm')}}</button>	
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.front') 




@push('head')

@endpush




@push('script')
<script type="text/javascript">
	  
    $(function(){
       $("#add_white_area").css('display','block');
      
    }) 

	
</script>


@endpush



@section('content')
	   


@endsection